### ISSUE TITLE
Some minor issues

### ISSUE THREAD

**Issue by therealharpaljadeja** [celo-org/ethglobal-istanbul#17]
```[tasklist]
### Tasks
- [x] Spinner for Lookup
- [x] Title for Settler field
- [x] Change settler to something else
- [x] Disable Add if invalid input
```
