### ISSUE TITLE
Add Readme with resources for hackers!

### ISSUE THREAD

**Issue by therealharpaljadeja** [celo-org/ethglobal-istanbul#8]
Provide resources that hackers would need in order to suceed at the hackathon!
```[tasklist]
### Tasks
- [x] ETHGlobal Hero Image
- [x] What is Celo
- [x] Bounty details
- [x] Workshop timing
- [x] Celo Composer - (Getting Started, Intro to Celo ETHGlobal Guide)
- [x] SocialConnect (Contract Addresses, Code Examples, Videos, DEK Setup, Cheatsheet, Ideas)
- [x] MiniPay (Build on MiniPay doc, How to get mainnet cUSD, Ideas)
- [ ] Valora (Ideas, Guides, Judging Criteria)
- [x] Account Abstraction (Cheatsheet, Thirdweb docs/RPC urls, Candide Bundler (RPC urls, docs & sheet), Pimlico docs
- [x] Judging Criteria
```
